/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_swisscom_eos_EosNativeBridge */

#ifndef _Included_com_swisscom_eos_EosNativeBridge
#define _Included_com_swisscom_eos_EosNativeBridge
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_swisscom_eos_EosNativeBridge
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_swisscom_eos_EosNativeBridge_init
  (JNIEnv *, jobject);

/*
 * Class:     com_swisscom_eos_EosNativeBridge
 * Method:    deinit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_swisscom_eos_EosNativeBridge_deinit
  (JNIEnv *, jobject);

/*
 * Class:     com_swisscom_eos_EosNativeBridge
 * Method:    start
 * Signature: (Lcom/swisscom/eos/out/EosOut;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_swisscom_eos_EosNativeBridge_start
  (JNIEnv *, jobject, jobject, jstring, jstring);

/*
 * Class:     com_swisscom_eos_EosNativeBridge
 * Method:    startBuffering
 * Signature: (Lcom/swisscom/eos/out/EosOut;)V
 */
JNIEXPORT void JNICALL Java_com_swisscom_eos_EosNativeBridge_startBuffering
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_swisscom_eos_EosNativeBridge
 * Method:    stopBuffering
 * Signature: (Lcom/swisscom/eos/out/EosOut;)V
 */
JNIEXPORT void JNICALL Java_com_swisscom_eos_EosNativeBridge_stopBuffering
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_swisscom_eos_EosNativeBridge
 * Method:    trickPlay
 * Signature: (Lcom/swisscom/eos/out/EosOut;JS)V
 */
JNIEXPORT void JNICALL Java_com_swisscom_eos_EosNativeBridge_trickPlay
  (JNIEnv *, jobject, jobject, jlong, jshort);

/*
 * Class:     com_swisscom_eos_EosNativeBridge
 * Method:    stop
 * Signature: (Lcom/swisscom/eos/out/EosOut;)V
 */
JNIEXPORT void JNICALL Java_com_swisscom_eos_EosNativeBridge_stop
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_swisscom_eos_EosNativeBridge
 * Method:    getMediaDesc
 * Signature: (Lcom/swisscom/eos/out/EosOut;)Lcom/swisscom/eos/media/EosMediaDesc;
 */
JNIEXPORT jobject JNICALL Java_com_swisscom_eos_EosNativeBridge_getMediaDesc
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_swisscom_eos_EosNativeBridge
 * Method:    selectTrack
 * Signature: (Lcom/swisscom/eos/out/EosOut;I)V
 */
JNIEXPORT void JNICALL Java_com_swisscom_eos_EosNativeBridge_selectTrack
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     com_swisscom_eos_EosNativeBridge
 * Method:    deselectTrack
 * Signature: (Lcom/swisscom/eos/out/EosOut;I)V
 */
JNIEXPORT void JNICALL Java_com_swisscom_eos_EosNativeBridge_deselectTrack
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     com_swisscom_eos_EosNativeBridge
 * Method:    setTtxtEnabled
 * Signature: (Lcom/swisscom/eos/out/EosOut;Z)V
 */
JNIEXPORT void JNICALL Java_com_swisscom_eos_EosNativeBridge_setTtxtEnabled
  (JNIEnv *, jobject, jobject, jboolean);

/*
 * Class:     com_swisscom_eos_EosNativeBridge
 * Method:    getTtxtPage
 * Signature: (Lcom/swisscom/eos/out/EosOut;I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_swisscom_eos_EosNativeBridge_getTtxtPage
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     com_swisscom_eos_EosNativeBridge
 * Method:    setTtxtPage
 * Signature: (Lcom/swisscom/eos/out/EosOut;II)V
 */
JNIEXPORT void JNICALL Java_com_swisscom_eos_EosNativeBridge_setTtxtPage
  (JNIEnv *, jobject, jobject, jint, jint);

/*
 * Class:     com_swisscom_eos_EosNativeBridge
 * Method:    getTtxtPageNumber
 * Signature: (Lcom/swisscom/eos/out/EosOut;)I
 */
JNIEXPORT jint JNICALL Java_com_swisscom_eos_EosNativeBridge_getTtxtPageNumber
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_swisscom_eos_EosNativeBridge
 * Method:    getTtxtSubPageNumber
 * Signature: (Lcom/swisscom/eos/out/EosOut;)I
 */
JNIEXPORT jint JNICALL Java_com_swisscom_eos_EosNativeBridge_getTtxtSubPageNumber
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_swisscom_eos_EosNativeBridge
 * Method:    getTtxtNextPage
 * Signature: (Lcom/swisscom/eos/out/EosOut;)I
 */
JNIEXPORT jint JNICALL Java_com_swisscom_eos_EosNativeBridge_getTtxtNextPage
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_swisscom_eos_EosNativeBridge
 * Method:    getTtxtPreviousPage
 * Signature: (Lcom/swisscom/eos/out/EosOut;)I
 */
JNIEXPORT jint JNICALL Java_com_swisscom_eos_EosNativeBridge_getTtxtPreviousPage
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_swisscom_eos_EosNativeBridge
 * Method:    getTtxtRedPage
 * Signature: (Lcom/swisscom/eos/out/EosOut;)I
 */
JNIEXPORT jint JNICALL Java_com_swisscom_eos_EosNativeBridge_getTtxtRedPage
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_swisscom_eos_EosNativeBridge
 * Method:    getTtxtGreenPage
 * Signature: (Lcom/swisscom/eos/out/EosOut;)I
 */
JNIEXPORT jint JNICALL Java_com_swisscom_eos_EosNativeBridge_getTtxtGreenPage
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_swisscom_eos_EosNativeBridge
 * Method:    getTtxtBluePage
 * Signature: (Lcom/swisscom/eos/out/EosOut;)I
 */
JNIEXPORT jint JNICALL Java_com_swisscom_eos_EosNativeBridge_getTtxtBluePage
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_swisscom_eos_EosNativeBridge
 * Method:    getTtxtYellowPage
 * Signature: (Lcom/swisscom/eos/out/EosOut;)I
 */
JNIEXPORT jint JNICALL Java_com_swisscom_eos_EosNativeBridge_getTtxtYellowPage
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_swisscom_eos_EosNativeBridge
 * Method:    getTtxtNextSubPageNumber
 * Signature: (Lcom/swisscom/eos/out/EosOut;)I
 */
JNIEXPORT jint JNICALL Java_com_swisscom_eos_EosNativeBridge_getTtxtNextSubPageNumber
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_swisscom_eos_EosNativeBridge
 * Method:    getTtxtPeviousSubPageNumber
 * Signature: (Lcom/swisscom/eos/out/EosOut;)I
 */
JNIEXPORT jint JNICALL Java_com_swisscom_eos_EosNativeBridge_getTtxtPeviousSubPageNumber
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_swisscom_eos_EosNativeBridge
 * Method:    setTtxtTransparency
 * Signature: (Lcom/swisscom/eos/out/EosOut;I)V
 */
JNIEXPORT void JNICALL Java_com_swisscom_eos_EosNativeBridge_setTtxtTransparency
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     com_swisscom_eos_EosNativeBridge
 * Method:    setDvbSubtitlesEnabled
 * Signature: (Lcom/swisscom/eos/out/EosOut;Z)V
 */
JNIEXPORT void JNICALL Java_com_swisscom_eos_EosNativeBridge_setDvbSubtitlesEnabled
  (JNIEnv *, jobject, jobject, jboolean);

/*
 * Class:     com_swisscom_eos_EosNativeBridge
 * Method:    setupVideo
 * Signature: (Lcom/swisscom/eos/out/EosOut;IIII)V
 */
JNIEXPORT void JNICALL Java_com_swisscom_eos_EosNativeBridge_setupVideo
  (JNIEnv *, jclass, jobject, jint, jint, jint, jint);

/*
 * Class:     com_swisscom_eos_EosNativeBridge
 * Method:    setAudioPassThrough
 * Signature: (Lcom/swisscom/eos/out/EosOut;Z)V
 */
JNIEXPORT void JNICALL Java_com_swisscom_eos_EosNativeBridge_setAudioPassThrough
  (JNIEnv *, jclass, jobject, jboolean);

/*
 * Class:     com_swisscom_eos_EosNativeBridge
 * Method:    setVolumeLeveling
 * Signature: (Lcom/swisscom/eos/out/EosOut;ZI)V
 */
JNIEXPORT void JNICALL Java_com_swisscom_eos_EosNativeBridge_setVolumeLeveling
  (JNIEnv *, jclass, jobject, jboolean, jint);

/*
 * Class:     com_swisscom_eos_EosNativeBridge
 * Method:    getVersion
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_swisscom_eos_EosNativeBridge_getVersion
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
